# Generated by Django 2.1.4 on 2019-01-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudjugadores', '0002_auto_20190128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
